name: 'Max Commit Count'
description: 'A GitHub action that requires that a PR contain no more than a specified number of commits'
author: 'Nikolai Wotton'
inputs:
  maxCommits:
    required: true
    description: 'The maximum number of commits allowed'
  token:
    required: false
    description: 'Defines the token to use to execute the git API requests with, uses `env.GITHUB_TOKEN` by default'
runs:
  using: 'node12'
  main: 'dist/index.js'
