name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_TOKEN }}
      - shell: bash
        name: "re-attach head"
        run: |
          git config --global user.email "automation@example.notARealEmail"
          git config --global user.name "Automation McBotterson"
          git config --global pull.rebase true
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
      - uses: burrunan/gradle-cache-action@v1
        name: Build with Cache
        with:
          read-only: ${{ github.ref != 'refs/heads/main' }}
          concurrent: true
          arguments: assemble --stacktrace --no-daemon
      - shell: bash
        name: "Commit changes back to PR"
        run: |
          git fetch
          git diff ${{ github.head_ref }} "origin/${{ github.head_ref }}" --exit-code || {
              echo "A new commit was pushed to this branch before this action completed"
              exit 1
          }
          [[ "$(git log -1 --pretty=format:'%ae')" == "automation@example.notARealEmail" ]] && {
              echo "The last commit was already made by automation"
              exit 0
          }
          git diff --exit-code || {
            git add .
            git commit -m "ci(dist): updating dist code [AUTO-258]"
            git push -u origin ${{ github.head_ref }}
          }
