name: Testing Self

on:
  pull_request:
    branches:
      - main

jobs:
  testing-self:
    runs-on: ubuntu-latest
    steps:
      - uses: nikwotton/Max-Commit-Count
        with:
          maxCommits: 3
          token: ${{ secrets.GITHUB_TOKEN }}
